rem @echo off 
rem a homemade batch file 
call buildone prog 3MBRIDGE 
call buildone prog 555TIMER 
call buildone prog ACCALC 
call buildone prog ACCELR 
call buildone prog ACTARING 
call buildone prog ADDONS 
call buildone prog AIRCORE 
call buildone prog AMDEX 
call buildone prog ANTENNA 
call buildone prog ANTFIELD 
call buildone prog antimp 
call buildone prog ANTMATCH 
call buildone prog ANTSCALE 
call buildone prog ANTSYN2 
call buildone prog ARCH 
call buildone prog ATTENPAD 
call buildone prog ATTENU 
call buildone prog AUDFILT 
call buildone prog AUDOSC 
call buildone prog AUDOSC2 
call buildone prog AUDPASS 
call buildone prog AWGEXACT 
call buildone prog BANDQ 
call buildone prog BANDSTOP 
call buildone prog BANDWDTH 
call buildone prog BAROMTR 
call buildone prog BATCHG 
call buildone prog BATTCHG 
call buildone prog BATTERY 
call buildone prog BEAMDEFL 
call buildone prog BEAMSECT 
call buildone prog BELTDRIV 
call buildone prog BEND 
call buildone prog BEVANT 
call buildone prog BIGNUM 
call buildone prog BINARY 
call buildone prog binhop 
call buildone prog BINVOL 
call buildone prog BOBTAIL 
call buildone prog BOOM 
call buildone prog BRICK 
call buildone prog BRIDGE-2 
call buildone prog BRIDGE 
call buildone prog BROADFER 
call buildone prog BROADFWE 
call buildone prog BUTTFILT 
call buildone prog BUXTON 
call buildone prog BUXTRAP 
call buildone prog BUYSELL 
call buildone prog CAL-X 
call buildone prog CALORY 
call buildone prog CALTODAY 
call buildone prog CAPACVAL 
call buildone prog CAPCOAX 
call buildone prog CAPSTRAY 
call buildone prog CAPTANCE 
call buildone prog CAPVAL 
call buildone prog CAPYHAT 
call buildone prog CAPYTEL 
call buildone prog CASCAMP 
call buildone prog CATENARY 
call buildone prog CCDANTEN 
call buildone prog CENTFREQ 
call buildone prog CENTLOAD 
call buildone prog CENTRIF 
call buildone prog CHAIN 
call buildone prog CHASE 
call buildone prog CHKLIST 
call buildone prog CHOKBAL 
call buildone prog CILDSGN 
call buildone prog CIRCFEED 
call buildone prog CLAMP 
call buildone prog CLARKY 
call buildone prog CLILDSGN 
call buildone prog CMOSC3 
call buildone prog COAXCALC 
call buildone prog COAXCHAR 
call buildone prog COAXLC3 
call buildone prog COAXSPEC 
call buildone prog COAXSTUB 
call buildone prog COAXTRAP 
call buildone prog COILAMP 
call buildone prog COILCPL 
call buildone prog COILDSGN 
call buildone prog COILEQUA 
call buildone prog COILIN 
call buildone prog COILNEW 
call buildone prog COILQ 
call buildone prog COILQUIK 
call buildone prog COILTAP 
call buildone prog COILTRUE 
call buildone prog COILX 
call buildone prog COLCODE 
call buildone prog COLPOSC 
call buildone prog COMFILT 
call buildone prog COMPINT 
call buildone prog CONCUR 
call buildone prog CONECALC 
call buildone prog CONJUMAT 
call buildone prog COOILDSG 
call buildone prog COPWIRE 
call buildone prog COXSTUB 
call buildone prog CPLRES 
call buildone prog CRYSFILT 
call buildone prog CURVEFIT 
call buildone prog CUSTCAP 
call buildone prog CUSTOHM 
call buildone prog CW 
call buildone prog CYL 
call buildone prog CYLLOAD 
call buildone prog DAYDUSK 
call buildone prog DAYS 
call buildone prog DBLBRG4 
call buildone prog DBLFB 
call buildone prog DECIBEL 
call buildone prog DECICONV 
call buildone prog DECIFRAC 
call buildone prog DELTAMAT 
call buildone prog DELTLOAD 
call buildone prog DEPREC 
call buildone prog DIALGTH 
call buildone prog DIAMFIND 
call buildone prog DIELECT 
call buildone prog DIPOL160 
call buildone prog DISCONE 
call buildone prog DISHANT 
call buildone prog DPEEDTD 
call buildone prog DSGNMENU 
call buildone prog DSGNRC 
call buildone prog DSGNRLC 
call buildone prog DUOPOLE 
call buildone prog DUOPWR 
call buildone prog ELECLENG 
call buildone prog ELECOST 
call buildone prog ELFLASH 
call buildone prog ELSPEC 
call buildone prog EQUIV 
call buildone prog ES2B 
call buildone prog EXIT 
call buildone prog EXPOSURE 
call buildone prog fail 
call buildone prog FATDIPOL 
call buildone prog FIBON 
call buildone prog FILSTRIP 
call buildone prog FILTER 
call buildone prog FILTRLC 
call buildone prog FILTUT 
call buildone prog FINANCE 
call buildone prog FISHBONE 
call buildone prog FOCUS 
call buildone prog FOLDIPOL 
call buildone prog FORMULAE 
call buildone prog FOROMENU 
call buildone prog FOTOCOPY 
call buildone prog FOTOMENU 
call buildone prog FOTOMOVE 
call buildone prog FOXLOG 
call buildone prog FUSEWIRE 
call buildone prog G5RV 
call buildone prog GAMMATCH 
call buildone prog GAPLOT 
call buildone prog GEARING 
call buildone prog GRAPHS 
call buildone prog GRIDSQ 
call buildone prog GUYWIRES 
call buildone prog HAIRPIN 
call buildone prog HALFLOOP 
call buildone prog HAMBANDS 
call buildone prog HAMCAL-X 
call buildone prog HAMCALC 
call buildone prog HAMDEX 
call buildone prog HARMONIC 
call buildone prog HARTOSC 
call buildone prog HARTOSC3 
call buildone prog HATSHAPE 
call buildone prog HCA 
call buildone prog HCAL-1 
call buildone prog HCAL-A 
call buildone prog HCAL-B 
call buildone prog HCAL-C 
call buildone prog HCAL-D 
call buildone prog HCAL-E 
call buildone prog HCAL-F 
call buildone prog HCAL-G 
call buildone prog HCAL-H 
call buildone prog HCAL-I 
call buildone prog HCAL-X 
call buildone prog HCAL-Z 
call buildone prog HCAL 
call buildone prog HCALC 
call buildone prog HELANT 
call buildone prog HELIX 
call buildone prog HELPHINT 
call buildone prog HELRESON 
call buildone prog HELVERT 
call buildone prog HOTBOX 
call buildone prog HUMID 
call buildone prog HXINSTAL 
call buildone prog IMPANT 
call buildone prog IMPARES 
call buildone prog IMPEDCCT 
call buildone prog IMPEDMET 
call buildone prog IMPEDNET 
call buildone prog INDUCALC 
call buildone prog INDUHOSE 
call buildone prog INDULOOP 
call buildone prog INLOSS 
call buildone prog INSERLOS 
call buildone prog INTRO 
call buildone prog INVEE 
call buildone prog INVOLUTE 
call buildone prog JAYPOLE 
call buildone prog JCALC 
call buildone prog KFACTOR 
call buildone prog L-PAD 
call buildone prog LADANT 
call buildone prog LADDER2 
call buildone prog LADRSOLV 
call buildone prog LAMPLIFE 
call buildone prog LATLONG 
call buildone prog LED 
call buildone prog LENSES 
call buildone prog LENSRING 
call buildone prog LINELOSS 
call buildone prog LINKUPL 
call buildone prog LIST10 
call buildone prog LM17 
call buildone prog LM315 
call buildone prog LM317 
call buildone prog LM317RUN 
call buildone prog LOANPAY 
call buildone prog LOCALRPT 
call buildone prog LOGOCLOK 
call buildone prog LOGYAG 
call buildone prog LOOPANT 
call buildone prog LOOPSKY 
call buildone prog LOOPXMIT 
call buildone prog LOPASS 
call buildone prog LOSSY 
call buildone prog LPTSETUP 
call buildone prog MATCHBOX 
call buildone prog MATCHNET 
call buildone prog MATFILT 
call buildone prog MATRICS 
call buildone prog MAXUF 
call buildone prog MECHMENU 
call buildone prog METERS 
call buildone prog METNOM 
call buildone prog METRICS 
call buildone prog METSHOWR 
call buildone prog MICLOOP 
call buildone prog MICROVER 
call buildone prog MINILOOP 
call buildone prog MINIQUAD 
call buildone prog MISMAT 
call buildone prog MIWHIP 
call buildone prog MOBILMAT 
call buildone prog MOONTRAC 
call buildone prog MORTGAG 
call buildone prog MOWHIP 
call buildone prog MOXON 
call buildone prog NEWSINCE 
call buildone prog NICAD 
call buildone prog NMBRSIZE 
call buildone prog NODE 
call buildone prog NOISFIG 
call buildone prog NOLOSS 
call buildone prog NUMDERIV 
call buildone prog NUMSORT 
call buildone prog OCFDIPOL 
call buildone prog OCTAGON 
call buildone prog OCTALOOP 
call buildone prog OCTARING 
call buildone prog OHMSLAW 
call buildone prog OPAMP 
call buildone prog OPENWIRE 
call buildone prog PAGE437 
call buildone prog PAIRLT 
call buildone prog PATHFIND 
call buildone prog PBA 
call buildone prog PEDOM 
call buildone prog PHAZDIFF 
call buildone prog PIMATCH 
call buildone prog PIPESIZE 
call buildone prog PITNET 
call buildone prog PIXEL 
call buildone prog POLYGON 
call buildone prog POTENT 
call buildone prog POWRXFMR 
call buildone prog PRACOSC 
call buildone prog PRECICAP 
call buildone prog PRECIRES 
call buildone prog PRIMENOS 
call buildone prog PRINTIP 
call buildone prog PROG 
call buildone prog PROPCIRC 
call buildone prog PRT 
call buildone prog PSUP 
call buildone prog PSUPERF 
call buildone prog PSYCHROM 
call buildone prog PULSEGEN 
call buildone prog PWRCCT 
call buildone prog PWRDIV 
call buildone prog PWRSUPP 
call buildone prog PWRXFMR 
call buildone prog Q 
call buildone prog QFACTOR 
call buildone prog QFIND 
call buildone prog QFIND5 
call buildone prog QLINE2 
call buildone prog QNTIMP 
call buildone prog QRESON 
call buildone prog QSK 
call buildone prog QTRAP 
call buildone prog QTRAPRUN 
call buildone prog QUAD 
call buildone prog QUADRAT 
call buildone prog QUARTWAV 
call buildone prog QUIKTABL 
call buildone prog RADANGLE 
call buildone prog RADIOLOS 
call buildone prog RANDNUM 
call buildone prog RCCONST 
call buildone prog RCFILT 
call buildone prog RCLOAD2 
call buildone prog REACT 
call buildone prog REMIND 
call buildone prog REMSIG 
call buildone prog RESICOP 
call buildone prog RESISTIV 
call buildone prog RESISVAL 
call buildone prog RIPPLE 
call buildone prog RISESET 
call buildone prog RJD 
call buildone prog ROTAPLOT 
call buildone prog RUN 
call buildone prog SATORBIT 
call buildone prog SCALSPD 
call buildone prog SCHMIDT 
call buildone prog SEASONS 
call buildone prog SEPAQ 
call buildone prog SERISECT 
call buildone prog SERPAR-Q 
call buildone prog SERSECT 
call buildone prog SHAFT 
call buildone prog SHORTANT 
call buildone prog SHORTDIP 
call buildone prog SHUTTLE 
call buildone prog SIMULEQ 
call buildone prog SINK 
call buildone prog SKIPDIST 
call buildone prog SLOPER 
call buildone prog SMETER 
call buildone prog SMITHCHT 
call buildone prog SNGLWIRE 
call buildone prog SOLUTRI 
call buildone prog SORTER 
call buildone prog SPARK 
call buildone prog SPEAKR 
call buildone prog SPEEDTD 
call buildone prog SQCOAX 
call buildone prog SQLINE 
call buildone prog STAIRS 
call buildone prog STUBANT 
call buildone prog SUNUP 
call buildone prog SURVEY 
call buildone prog SWR 
call buildone prog T2FD 
call buildone prog TANKCCT 
call buildone prog TEEMATCH 
call buildone prog TELETUBE 
call buildone prog TEST 
call buildone prog TFORM3 
call buildone prog THERMRES 
call buildone prog THEVININ 
call buildone prog THRUBOOM 
call buildone prog TIMEQ 
call buildone prog TIMEZONE 
call buildone prog TINYCOIL 
call buildone prog TITLER 
call buildone prog TJD 
call buildone prog TMATCH 
call buildone prog TOROID 
call buildone prog TOROTRAP 
call buildone prog TORQUE 
call buildone prog TRACKER 
call buildone prog TRANCCT 
call buildone prog TRANLINE 
call buildone prog TRANSMAT 
call buildone prog TRANSTUB 
call buildone prog TRAPCALC 
call buildone prog TRAPDSGN 
call buildone prog TRAPOLE 
call buildone prog TRAPROP 
call buildone prog TRIG 
call buildone prog TRIMR 
call buildone prog TRIPLAN 
call buildone prog TRISQU 
call buildone prog TRUNORTH 
call buildone prog TSFD 
call buildone prog TUNECCT 
call buildone prog TURNRAD 
call buildone prog TURNS 
call buildone prog TVCHAN 
call buildone prog TWINTEE 
call buildone prog UNITVALU 
call buildone prog VACAP 
call buildone prog VACAP14 
call buildone prog VACAP7 
call buildone prog VACAP8 
call buildone prog VACAP9 
call buildone prog VARAYFED 
call buildone prog VERTPATT 
call buildone prog VFOFREQ 
call buildone prog VOLTDIV 
call buildone prog WALKER 
call buildone prog WALWART 
call buildone prog WARTEST 
call buildone prog WATCH 
call buildone prog WAVETRAP 
call buildone prog WHEATSTO 
call buildone prog WINCHIL 
call buildone prog WINDCHIL 
call buildone prog WINDING 
call buildone prog WINDOM 
call buildone prog WIREANT 
call buildone prog WIRECOND 
call buildone prog WIREMESH 
call buildone prog WIREPEOP 
call buildone prog WIREPROP 
call buildone prog WIRESAG 
call buildone prog WORKS 
call buildone prog WX 
call buildone prog XFMR 
call buildone prog XFMRNARO 
call buildone prog XMTRZMAT 
call buildone prog XOVER 
call buildone prog YAGI3EL 
call buildone prog YAGILONG 
call buildone prog YAGISPAC 
call buildone prog YAGLONG 
call buildone prog YAGTAPER 
call buildone prog ZENER 
call buildone prog ZEPP 
call buildone prog ZEPPDBL 
call buildone prog ZEXIT 
call buildone prog ZOSTEPUP 
call buildone prog zounds 
