rem @echo off 
rem a homemade batch file 
movecom \hamcalc64\prog\DECIFRAC.old \hamcalc64\prog\DECIFRAC.BAS 
movecom \hamcalc64\prog\DELTAMAT.old \hamcalc64\prog\DELTAMAT.BAS 
movecom \hamcalc64\prog\DELTLOAD.old \hamcalc64\prog\DELTLOAD.BAS 
movecom \hamcalc64\prog\DEPREC.old \hamcalc64\prog\DEPREC.BAS 
movecom \hamcalc64\prog\DIALGTH.old \hamcalc64\prog\DIALGTH.BAS 
movecom \hamcalc64\prog\DIAMFIND.old \hamcalc64\prog\DIAMFIND.BAS 
movecom \hamcalc64\prog\DIELECT.old \hamcalc64\prog\DIELECT.BAS 
movecom \hamcalc64\prog\DIPOL160.old \hamcalc64\prog\DIPOL160.BAS 
movecom \hamcalc64\prog\DISCONE.old \hamcalc64\prog\DISCONE.BAS 
movecom \hamcalc64\prog\DISHANT.old \hamcalc64\prog\DISHANT.BAS 
movecom \hamcalc64\prog\DPEEDTD.old \hamcalc64\prog\DPEEDTD.BAS 
movecom \hamcalc64\prog\DSGNMENU.old \hamcalc64\prog\DSGNMENU.BAS 
movecom \hamcalc64\prog\DSGNRC.old \hamcalc64\prog\DSGNRC.BAS 
movecom \hamcalc64\prog\DSGNRLC.old \hamcalc64\prog\DSGNRLC.BAS 
movecom \hamcalc64\prog\DUOPOLE.old \hamcalc64\prog\DUOPOLE.BAS 
movecom \hamcalc64\prog\DUOPWR.old \hamcalc64\prog\DUOPWR.BAS 
movecom \hamcalc64\prog\ELECLENG.old \hamcalc64\prog\ELECLENG.BAS 
movecom \hamcalc64\prog\ELECOST.old \hamcalc64\prog\ELECOST.BAS 
movecom \hamcalc64\prog\ELFLASH.old \hamcalc64\prog\ELFLASH.BAS 
movecom \hamcalc64\prog\ELSPEC.old \hamcalc64\prog\ELSPEC.BAS 
movecom \hamcalc64\prog\EQUIV.old \hamcalc64\prog\EQUIV.BAS 
movecom \hamcalc64\prog\ES2B.old \hamcalc64\prog\ES2B.BAS 
movecom \hamcalc64\prog\EXIT.old \hamcalc64\prog\EXIT.BAS 
movecom \hamcalc64\prog\EXPOSURE.old \hamcalc64\prog\EXPOSURE.BAS 
movecom \hamcalc64\prog\FATDIPOL.old \hamcalc64\prog\FATDIPOL.BAS 
movecom \hamcalc64\prog\FIBON.old \hamcalc64\prog\FIBON.BAS 
movecom \hamcalc64\prog\FILSTRIP.old \hamcalc64\prog\FILSTRIP.BAS 
movecom \hamcalc64\prog\FILTER.old \hamcalc64\prog\FILTER.BAS 
movecom \hamcalc64\prog\FILTRLC.old \hamcalc64\prog\FILTRLC.BAS 
movecom \hamcalc64\prog\FILTUT.old \hamcalc64\prog\FILTUT.BAS 
movecom \hamcalc64\prog\FINANCE.old \hamcalc64\prog\FINANCE.BAS 
movecom \hamcalc64\prog\FISHBONE.old \hamcalc64\prog\FISHBONE.BAS 
movecom \hamcalc64\prog\FOCUS.old \hamcalc64\prog\FOCUS.BAS 
movecom \hamcalc64\prog\FOLDIPOL.old \hamcalc64\prog\FOLDIPOL.BAS 
movecom \hamcalc64\prog\FORMULAE.old \hamcalc64\prog\FORMULAE.BAS 
movecom \hamcalc64\prog\FOROMENU.old \hamcalc64\prog\FOROMENU.BAS 
movecom \hamcalc64\prog\FOTOCOPY.old \hamcalc64\prog\FOTOCOPY.BAS 
movecom \hamcalc64\prog\FOTOMENU.old \hamcalc64\prog\FOTOMENU.BAS 
movecom \hamcalc64\prog\FOTOMOVE.old \hamcalc64\prog\FOTOMOVE.BAS 
movecom \hamcalc64\prog\FOXLOG.old \hamcalc64\prog\FOXLOG.BAS 
movecom \hamcalc64\prog\FUSEWIRE.old \hamcalc64\prog\FUSEWIRE.BAS 
movecom \hamcalc64\prog\G5RV.old \hamcalc64\prog\G5RV.BAS 
movecom \hamcalc64\prog\GAMMATCH.old \hamcalc64\prog\GAMMATCH.BAS 
movecom \hamcalc64\prog\GAPLOT.old \hamcalc64\prog\GAPLOT.BAS 
movecom \hamcalc64\prog\GEARING.old \hamcalc64\prog\GEARING.BAS 
movecom \hamcalc64\prog\GRAPHS.old \hamcalc64\prog\GRAPHS.BAS 
movecom \hamcalc64\prog\GRIDSQ.old \hamcalc64\prog\GRIDSQ.BAS 
movecom \hamcalc64\prog\GUYWIRES.old \hamcalc64\prog\GUYWIRES.BAS 
movecom \hamcalc64\prog\HAIRPIN.old \hamcalc64\prog\HAIRPIN.BAS 
movecom \hamcalc64\prog\HALFLOOP.old \hamcalc64\prog\HALFLOOP.BAS 
movecom \hamcalc64\prog\HAMBANDS.old \hamcalc64\prog\HAMBANDS.BAS 
movecom \hamcalc64\prog\HAMCALC.old \hamcalc64\prog\HAMCALC.BAS 
movecom \hamcalc64\prog\HAMDEX.old \hamcalc64\prog\HAMDEX.BAS 
movecom \hamcalc64\prog\HARMONIC.old \hamcalc64\prog\HARMONIC.BAS 
movecom \hamcalc64\prog\HARTOSC.old \hamcalc64\prog\HARTOSC.BAS 
movecom \hamcalc64\prog\HARTOSC3.old \hamcalc64\prog\HARTOSC3.BAS 
movecom \hamcalc64\prog\HATSHAPE.old \hamcalc64\prog\HATSHAPE.BAS 
movecom \hamcalc64\prog\HCAL-X.old \hamcalc64\prog\HCAL-X.BAS 
movecom \hamcalc64\prog\HCAL.old \hamcalc64\prog\HCAL.BAS 
movecom \hamcalc64\prog\HELANT.old \hamcalc64\prog\HELANT.BAS 
movecom \hamcalc64\prog\HELIX.old \hamcalc64\prog\HELIX.BAS 
movecom \hamcalc64\prog\HELPHINT.old \hamcalc64\prog\HELPHINT.BAS 
movecom \hamcalc64\prog\HELRESON.old \hamcalc64\prog\HELRESON.BAS 
movecom \hamcalc64\prog\HELVERT.old \hamcalc64\prog\HELVERT.BAS 
movecom \hamcalc64\prog\HOTBOX.old \hamcalc64\prog\HOTBOX.BAS 
movecom \hamcalc64\prog\HUMID.old \hamcalc64\prog\HUMID.BAS 
movecom \hamcalc64\prog\HXINSTAL.old \hamcalc64\prog\HXINSTAL.BAS 
movecom \hamcalc64\prog\IMPANT.old \hamcalc64\prog\IMPANT.BAS 
movecom \hamcalc64\prog\IMPARES.old \hamcalc64\prog\IMPARES.BAS 
movecom \hamcalc64\prog\IMPEDCCT.old \hamcalc64\prog\IMPEDCCT.BAS 
movecom \hamcalc64\prog\IMPEDMET.old \hamcalc64\prog\IMPEDMET.BAS 
movecom \hamcalc64\prog\IMPEDNET.old \hamcalc64\prog\IMPEDNET.BAS 
movecom \hamcalc64\prog\INDUCALC.old \hamcalc64\prog\INDUCALC.BAS 
movecom \hamcalc64\prog\INDUHOSE.old \hamcalc64\prog\INDUHOSE.BAS 
movecom \hamcalc64\prog\INDULOOP.old \hamcalc64\prog\INDULOOP.BAS 
movecom \hamcalc64\prog\INLOSS.old \hamcalc64\prog\INLOSS.BAS 
movecom \hamcalc64\prog\INSERLOS.old \hamcalc64\prog\INSERLOS.BAS 
movecom \hamcalc64\prog\INTRO.old \hamcalc64\prog\INTRO.BAS 
movecom \hamcalc64\prog\INVEE.old \hamcalc64\prog\INVEE.BAS 
movecom \hamcalc64\prog\INVOLUTE.old \hamcalc64\prog\INVOLUTE.BAS 
movecom \hamcalc64\prog\JAYPOLE.old \hamcalc64\prog\JAYPOLE.BAS 
movecom \hamcalc64\prog\JCALC.old \hamcalc64\prog\JCALC.BAS 
movecom \hamcalc64\prog\KFACTOR.old \hamcalc64\prog\KFACTOR.BAS 
movecom \hamcalc64\prog\L-PAD.old \hamcalc64\prog\L-PAD.BAS 
movecom \hamcalc64\prog\LADANT.old \hamcalc64\prog\LADANT.BAS 
movecom \hamcalc64\prog\LADDER2.old \hamcalc64\prog\LADDER2.BAS 
movecom \hamcalc64\prog\LADRSOLV.old \hamcalc64\prog\LADRSOLV.BAS 
movecom \hamcalc64\prog\LAMPLIFE.old \hamcalc64\prog\LAMPLIFE.BAS 
movecom \hamcalc64\prog\LATLONG.old \hamcalc64\prog\LATLONG.BAS 
movecom \hamcalc64\prog\LED.old \hamcalc64\prog\LED.BAS 
movecom \hamcalc64\prog\LENSES.old \hamcalc64\prog\LENSES.BAS 
movecom \hamcalc64\prog\LENSRING.old \hamcalc64\prog\LENSRING.BAS 
movecom \hamcalc64\prog\LINELOSS.old \hamcalc64\prog\LINELOSS.BAS 
movecom \hamcalc64\prog\LINKUPL.old \hamcalc64\prog\LINKUPL.BAS 
movecom \hamcalc64\prog\LIST10.old \hamcalc64\prog\LIST10.BAS 
movecom \hamcalc64\prog\LM17.old \hamcalc64\prog\LM17.BAS 
movecom \hamcalc64\prog\LM315.old \hamcalc64\prog\LM315.BAS 
movecom \hamcalc64\prog\LM317.old \hamcalc64\prog\LM317.BAS 
movecom \hamcalc64\prog\LM317RUN.old \hamcalc64\prog\LM317RUN.BAS 
movecom \hamcalc64\prog\LOANPAY.old \hamcalc64\prog\LOANPAY.BAS 
movecom \hamcalc64\prog\LOCALRPT.old \hamcalc64\prog\LOCALRPT.BAS 
movecom \hamcalc64\prog\LOGOCLOK.old \hamcalc64\prog\LOGOCLOK.BAS 
movecom \hamcalc64\prog\LOGYAG.old \hamcalc64\prog\LOGYAG.BAS 
movecom \hamcalc64\prog\LOOPANT.old \hamcalc64\prog\LOOPANT.BAS 
movecom \hamcalc64\prog\LOOPSKY.old \hamcalc64\prog\LOOPSKY.BAS 
movecom \hamcalc64\prog\LOOPXMIT.old \hamcalc64\prog\LOOPXMIT.BAS 
movecom \hamcalc64\prog\LOPASS.old \hamcalc64\prog\LOPASS.BAS 
movecom \hamcalc64\prog\LOSSY.old \hamcalc64\prog\LOSSY.BAS 
movecom \hamcalc64\prog\LPTSETUP.old \hamcalc64\prog\LPTSETUP.BAS 
movecom \hamcalc64\prog\MATCHBOX.old \hamcalc64\prog\MATCHBOX.BAS 
movecom \hamcalc64\prog\MATCHNET.old \hamcalc64\prog\MATCHNET.BAS 
movecom \hamcalc64\prog\MATFILT.old \hamcalc64\prog\MATFILT.BAS 
movecom \hamcalc64\prog\MATRICS.old \hamcalc64\prog\MATRICS.BAS 
movecom \hamcalc64\prog\MAXUF.old \hamcalc64\prog\MAXUF.BAS 
movecom \hamcalc64\prog\MECHMENU.old \hamcalc64\prog\MECHMENU.BAS 
movecom \hamcalc64\prog\METERS.old \hamcalc64\prog\METERS.BAS 
movecom \hamcalc64\prog\METNOM.old \hamcalc64\prog\METNOM.BAS 
movecom \hamcalc64\prog\METRICS.old \hamcalc64\prog\METRICS.BAS 
movecom \hamcalc64\prog\METSHOWR.old \hamcalc64\prog\METSHOWR.BAS 
movecom \hamcalc64\prog\MICLOOP.old \hamcalc64\prog\MICLOOP.BAS 
movecom \hamcalc64\prog\MICROVER.old \hamcalc64\prog\MICROVER.BAS 
movecom \hamcalc64\prog\MINILOOP.old \hamcalc64\prog\MINILOOP.BAS 
movecom \hamcalc64\prog\MINIQUAD.old \hamcalc64\prog\MINIQUAD.BAS 
movecom \hamcalc64\prog\MISMAT.old \hamcalc64\prog\MISMAT.BAS 
movecom \hamcalc64\prog\MIWHIP.old \hamcalc64\prog\MIWHIP.BAS 
movecom \hamcalc64\prog\MOBILMAT.old \hamcalc64\prog\MOBILMAT.BAS 
movecom \hamcalc64\prog\MOONTRAC.old \hamcalc64\prog\MOONTRAC.BAS 
movecom \hamcalc64\prog\MORTGAG.old \hamcalc64\prog\MORTGAG.BAS 
movecom \hamcalc64\prog\MOWHIP.old \hamcalc64\prog\MOWHIP.BAS 
movecom \hamcalc64\prog\MOXON.old \hamcalc64\prog\MOXON.BAS 
movecom \hamcalc64\prog\NEWSINCE.old \hamcalc64\prog\NEWSINCE.BAS 
movecom \hamcalc64\prog\NICAD.old \hamcalc64\prog\NICAD.BAS 
movecom \hamcalc64\prog\NMBRSIZE.old \hamcalc64\prog\NMBRSIZE.BAS 
movecom \hamcalc64\prog\NODE.old \hamcalc64\prog\NODE.BAS 
movecom \hamcalc64\prog\NOISFIG.old \hamcalc64\prog\NOISFIG.BAS 
movecom \hamcalc64\prog\NOLOSS.old \hamcalc64\prog\NOLOSS.BAS 
movecom \hamcalc64\prog\NUMDERIV.old \hamcalc64\prog\NUMDERIV.BAS 
movecom \hamcalc64\prog\NUMSORT.old \hamcalc64\prog\NUMSORT.BAS 
movecom \hamcalc64\prog\OCFDIPOL.old \hamcalc64\prog\OCFDIPOL.BAS 
movecom \hamcalc64\prog\OCTAGON.old \hamcalc64\prog\OCTAGON.BAS 
movecom \hamcalc64\prog\OCTALOOP.old \hamcalc64\prog\OCTALOOP.BAS 
movecom \hamcalc64\prog\OCTARING.old \hamcalc64\prog\OCTARING.BAS 
movecom \hamcalc64\prog\OHMSLAW.old \hamcalc64\prog\OHMSLAW.BAS 
movecom \hamcalc64\prog\OPAMP.old \hamcalc64\prog\OPAMP.BAS 
movecom \hamcalc64\prog\OPENWIRE.old \hamcalc64\prog\OPENWIRE.BAS 
movecom \hamcalc64\prog\PAGE437.old \hamcalc64\prog\PAGE437.BAS 
movecom \hamcalc64\prog\PAIRLT.old \hamcalc64\prog\PAIRLT.BAS 
movecom \hamcalc64\prog\PATHFIND.old \hamcalc64\prog\PATHFIND.BAS 
movecom \hamcalc64\prog\PBA.old \hamcalc64\prog\PBA.BAS 
movecom \hamcalc64\prog\PEDOM.old \hamcalc64\prog\PEDOM.BAS 
movecom \hamcalc64\prog\PHAZDIFF.old \hamcalc64\prog\PHAZDIFF.BAS 
movecom \hamcalc64\prog\PIMATCH.old \hamcalc64\prog\PIMATCH.BAS 
movecom \hamcalc64\prog\PIPESIZE.old \hamcalc64\prog\PIPESIZE.BAS 
movecom \hamcalc64\prog\PITNET.old \hamcalc64\prog\PITNET.BAS 
movecom \hamcalc64\prog\PIXEL.old \hamcalc64\prog\PIXEL.BAS 
movecom \hamcalc64\prog\POLYGON.old \hamcalc64\prog\POLYGON.BAS 
movecom \hamcalc64\prog\POTENT.old \hamcalc64\prog\POTENT.BAS 
movecom \hamcalc64\prog\POWRXFMR.old \hamcalc64\prog\POWRXFMR.BAS 
movecom \hamcalc64\prog\PRACOSC.old \hamcalc64\prog\PRACOSC.BAS 
movecom \hamcalc64\prog\PRECICAP.old \hamcalc64\prog\PRECICAP.BAS 
movecom \hamcalc64\prog\PRECIRES.old \hamcalc64\prog\PRECIRES.BAS 
movecom \hamcalc64\prog\PRIMENOS.old \hamcalc64\prog\PRIMENOS.BAS 
movecom \hamcalc64\prog\PRINTIP.old \hamcalc64\prog\PRINTIP.BAS 
movecom \hamcalc64\prog\PROPCIRC.old \hamcalc64\prog\PROPCIRC.BAS 
movecom \hamcalc64\prog\PRT.old \hamcalc64\prog\PRT.BAS 
movecom \hamcalc64\prog\PSUP.old \hamcalc64\prog\PSUP.BAS 
movecom \hamcalc64\prog\PSUPERF.old \hamcalc64\prog\PSUPERF.BAS 
movecom \hamcalc64\prog\PSYCHROM.old \hamcalc64\prog\PSYCHROM.BAS 
movecom \hamcalc64\prog\PULSEGEN.old \hamcalc64\prog\PULSEGEN.BAS 
movecom \hamcalc64\prog\PWRCCT.old \hamcalc64\prog\PWRCCT.BAS 
movecom \hamcalc64\prog\PWRDIV.old \hamcalc64\prog\PWRDIV.BAS 
movecom \hamcalc64\prog\PWRSUPP.old \hamcalc64\prog\PWRSUPP.BAS 
movecom \hamcalc64\prog\PWRXFMR.old \hamcalc64\prog\PWRXFMR.BAS 
movecom \hamcalc64\prog\Q.old \hamcalc64\prog\Q.BAS 
movecom \hamcalc64\prog\QFACTOR.old \hamcalc64\prog\QFACTOR.BAS 
movecom \hamcalc64\prog\QFIND.old \hamcalc64\prog\QFIND.BAS 
movecom \hamcalc64\prog\QFIND5.old \hamcalc64\prog\QFIND5.BAS 
movecom \hamcalc64\prog\QLINE2.old \hamcalc64\prog\QLINE2.BAS 
movecom \hamcalc64\prog\QNTIMP.old \hamcalc64\prog\QNTIMP.BAS 
movecom \hamcalc64\prog\QRESON.old \hamcalc64\prog\QRESON.BAS 
movecom \hamcalc64\prog\QSK.old \hamcalc64\prog\QSK.BAS 
movecom \hamcalc64\prog\QTRAP.old \hamcalc64\prog\QTRAP.BAS 
movecom \hamcalc64\prog\QTRAPRUN.old \hamcalc64\prog\QTRAPRUN.BAS 
movecom \hamcalc64\prog\QUAD.old \hamcalc64\prog\QUAD.BAS 
movecom \hamcalc64\prog\QUADRAT.old \hamcalc64\prog\QUADRAT.BAS 
movecom \hamcalc64\prog\QUARTWAV.old \hamcalc64\prog\QUARTWAV.BAS 
movecom \hamcalc64\prog\QUIKTABL.old \hamcalc64\prog\QUIKTABL.BAS 
movecom \hamcalc64\prog\RADANGLE.old \hamcalc64\prog\RADANGLE.BAS 
movecom \hamcalc64\prog\RADIOLOS.old \hamcalc64\prog\RADIOLOS.BAS 
movecom \hamcalc64\prog\RANDNUM.old \hamcalc64\prog\RANDNUM.BAS 
movecom \hamcalc64\prog\RCCONST.old \hamcalc64\prog\RCCONST.BAS 
movecom \hamcalc64\prog\RCFILT.old \hamcalc64\prog\RCFILT.BAS 
movecom \hamcalc64\prog\RCLOAD2.old \hamcalc64\prog\RCLOAD2.BAS 
movecom \hamcalc64\prog\REACT.old \hamcalc64\prog\REACT.BAS 
movecom \hamcalc64\prog\REMIND.old \hamcalc64\prog\REMIND.BAS 
movecom \hamcalc64\prog\REMSIG.old \hamcalc64\prog\REMSIG.BAS 
movecom \hamcalc64\prog\RESICOP.old \hamcalc64\prog\RESICOP.BAS 
movecom \hamcalc64\prog\RESISTIV.old \hamcalc64\prog\RESISTIV.BAS 
movecom \hamcalc64\prog\RESISVAL.old \hamcalc64\prog\RESISVAL.BAS 
movecom \hamcalc64\prog\RIPPLE.old \hamcalc64\prog\RIPPLE.BAS 
movecom \hamcalc64\prog\RISESET.old \hamcalc64\prog\RISESET.BAS 
movecom \hamcalc64\prog\RJD.old \hamcalc64\prog\RJD.BAS 
movecom \hamcalc64\prog\ROTAPLOT.old \hamcalc64\prog\ROTAPLOT.BAS 
movecom \hamcalc64\prog\RUN.old \hamcalc64\prog\RUN.BAS 
movecom \hamcalc64\prog\SATORBIT.old \hamcalc64\prog\SATORBIT.BAS 
movecom \hamcalc64\prog\SCALSPD.old \hamcalc64\prog\SCALSPD.BAS 
movecom \hamcalc64\prog\SCHMIDT.old \hamcalc64\prog\SCHMIDT.BAS 
movecom \hamcalc64\prog\SEASONS.old \hamcalc64\prog\SEASONS.BAS 
movecom \hamcalc64\prog\SEPAQ.old \hamcalc64\prog\SEPAQ.BAS 
movecom \hamcalc64\prog\SERISECT.old \hamcalc64\prog\SERISECT.BAS 
movecom \hamcalc64\prog\SERPAR-Q.old \hamcalc64\prog\SERPAR-Q.BAS 
movecom \hamcalc64\prog\SERSECT.old \hamcalc64\prog\SERSECT.BAS 
movecom \hamcalc64\prog\SHAFT.old \hamcalc64\prog\SHAFT.BAS 
movecom \hamcalc64\prog\SHORTANT.old \hamcalc64\prog\SHORTANT.BAS 
movecom \hamcalc64\prog\SHORTDIP.old \hamcalc64\prog\SHORTDIP.BAS 
movecom \hamcalc64\prog\SHUTTLE.old \hamcalc64\prog\SHUTTLE.BAS 
movecom \hamcalc64\prog\SIMULEQ.old \hamcalc64\prog\SIMULEQ.BAS 
movecom \hamcalc64\prog\SINK.old \hamcalc64\prog\SINK.BAS 
movecom \hamcalc64\prog\SKIPDIST.old \hamcalc64\prog\SKIPDIST.BAS 
movecom \hamcalc64\prog\SLOPER.old \hamcalc64\prog\SLOPER.BAS 
movecom \hamcalc64\prog\SMETER.old \hamcalc64\prog\SMETER.BAS 
movecom \hamcalc64\prog\SMITHCHT.old \hamcalc64\prog\SMITHCHT.BAS 
movecom \hamcalc64\prog\SNGLWIRE.old \hamcalc64\prog\SNGLWIRE.BAS 
movecom \hamcalc64\prog\SOLUTRI.old \hamcalc64\prog\SOLUTRI.BAS 
movecom \hamcalc64\prog\SORTER.old \hamcalc64\prog\SORTER.BAS 
movecom \hamcalc64\prog\SPARK.old \hamcalc64\prog\SPARK.BAS 
movecom \hamcalc64\prog\SPEAKR.old \hamcalc64\prog\SPEAKR.BAS 
movecom \hamcalc64\prog\SPEEDTD.old \hamcalc64\prog\SPEEDTD.BAS 
movecom \hamcalc64\prog\SQCOAX.old \hamcalc64\prog\SQCOAX.BAS 
movecom \hamcalc64\prog\SQLINE.old \hamcalc64\prog\SQLINE.BAS 
movecom \hamcalc64\prog\STAIRS.old \hamcalc64\prog\STAIRS.BAS 
movecom \hamcalc64\prog\STUBANT.old \hamcalc64\prog\STUBANT.BAS 
movecom \hamcalc64\prog\SUNUP.old \hamcalc64\prog\SUNUP.BAS 
movecom \hamcalc64\prog\SURVEY.old \hamcalc64\prog\SURVEY.BAS 
movecom \hamcalc64\prog\SWR.old \hamcalc64\prog\SWR.BAS 
movecom \hamcalc64\prog\T2FD.old \hamcalc64\prog\T2FD.BAS 
movecom \hamcalc64\prog\TANKCCT.old \hamcalc64\prog\TANKCCT.BAS 
movecom \hamcalc64\prog\TEEMATCH.old \hamcalc64\prog\TEEMATCH.BAS 
movecom \hamcalc64\prog\TELETUBE.old \hamcalc64\prog\TELETUBE.BAS 
movecom \hamcalc64\prog\TEST.old \hamcalc64\prog\TEST.BAS 
movecom \hamcalc64\prog\TFORM3.old \hamcalc64\prog\TFORM3.BAS 
movecom \hamcalc64\prog\THERMRES.old \hamcalc64\prog\THERMRES.BAS 
movecom \hamcalc64\prog\THEVININ.old \hamcalc64\prog\THEVININ.BAS 
movecom \hamcalc64\prog\THRUBOOM.old \hamcalc64\prog\THRUBOOM.BAS 
movecom \hamcalc64\prog\TIMEQ.old \hamcalc64\prog\TIMEQ.BAS 
movecom \hamcalc64\prog\TIMEZONE.old \hamcalc64\prog\TIMEZONE.BAS 
movecom \hamcalc64\prog\TINYCOIL.old \hamcalc64\prog\TINYCOIL.BAS 
movecom \hamcalc64\prog\TITLER.old \hamcalc64\prog\TITLER.BAS 
movecom \hamcalc64\prog\TJD.old \hamcalc64\prog\TJD.BAS 
movecom \hamcalc64\prog\TMATCH.old \hamcalc64\prog\TMATCH.BAS 
movecom \hamcalc64\prog\TOROID.old \hamcalc64\prog\TOROID.BAS 
movecom \hamcalc64\prog\TOROTRAP.old \hamcalc64\prog\TOROTRAP.BAS 
movecom \hamcalc64\prog\TORQUE.old \hamcalc64\prog\TORQUE.BAS 
movecom \hamcalc64\prog\TRACKER.old \hamcalc64\prog\TRACKER.BAS 
movecom \hamcalc64\prog\TRANCCT.old \hamcalc64\prog\TRANCCT.BAS 
movecom \hamcalc64\prog\TRANLINE.old \hamcalc64\prog\TRANLINE.BAS 
movecom \hamcalc64\prog\TRANSMAT.old \hamcalc64\prog\TRANSMAT.BAS 
movecom \hamcalc64\prog\TRANSTUB.old \hamcalc64\prog\TRANSTUB.BAS 
movecom \hamcalc64\prog\TRAPCALC.old \hamcalc64\prog\TRAPCALC.BAS 
movecom \hamcalc64\prog\TRAPDSGN.old \hamcalc64\prog\TRAPDSGN.BAS 
movecom \hamcalc64\prog\TRAPOLE.old \hamcalc64\prog\TRAPOLE.BAS 
movecom \hamcalc64\prog\TRAPROP.old \hamcalc64\prog\TRAPROP.BAS 
movecom \hamcalc64\prog\TRIG.old \hamcalc64\prog\TRIG.BAS 
movecom \hamcalc64\prog\TRIMR.old \hamcalc64\prog\TRIMR.BAS 
movecom \hamcalc64\prog\TRIPLAN.old \hamcalc64\prog\TRIPLAN.BAS 
movecom \hamcalc64\prog\TRISQU.old \hamcalc64\prog\TRISQU.BAS 
movecom \hamcalc64\prog\TRUNORTH.old \hamcalc64\prog\TRUNORTH.BAS 
movecom \hamcalc64\prog\TSFD.old \hamcalc64\prog\TSFD.BAS 
movecom \hamcalc64\prog\TUNECCT.old \hamcalc64\prog\TUNECCT.BAS 
movecom \hamcalc64\prog\TURNRAD.old \hamcalc64\prog\TURNRAD.BAS 
movecom \hamcalc64\prog\TURNS.old \hamcalc64\prog\TURNS.BAS 
movecom \hamcalc64\prog\TVCHAN.old \hamcalc64\prog\TVCHAN.BAS 
movecom \hamcalc64\prog\TWINTEE.old \hamcalc64\prog\TWINTEE.BAS 
movecom \hamcalc64\prog\UNITVALU.old \hamcalc64\prog\UNITVALU.BAS 
movecom \hamcalc64\prog\VACAP.old \hamcalc64\prog\VACAP.BAS 
movecom \hamcalc64\prog\VACAP14.old \hamcalc64\prog\VACAP14.BAS 
movecom \hamcalc64\prog\VACAP7.old \hamcalc64\prog\VACAP7.BAS 
movecom \hamcalc64\prog\VACAP8.old \hamcalc64\prog\VACAP8.BAS 
movecom \hamcalc64\prog\VACAP9.old \hamcalc64\prog\VACAP9.BAS 
movecom \hamcalc64\prog\VARAYFED.old \hamcalc64\prog\VARAYFED.BAS 
movecom \hamcalc64\prog\VERTPATT.old \hamcalc64\prog\VERTPATT.BAS 
movecom \hamcalc64\prog\VFOFREQ.old \hamcalc64\prog\VFOFREQ.BAS 
movecom \hamcalc64\prog\VOLTDIV.old \hamcalc64\prog\VOLTDIV.BAS 
movecom \hamcalc64\prog\WALKER.old \hamcalc64\prog\WALKER.BAS 
movecom \hamcalc64\prog\WALWART.old \hamcalc64\prog\WALWART.BAS 
movecom \hamcalc64\prog\WARTEST.old \hamcalc64\prog\WARTEST.BAS 
movecom \hamcalc64\prog\WATCH.old \hamcalc64\prog\WATCH.BAS 
movecom \hamcalc64\prog\WAVETRAP.old \hamcalc64\prog\WAVETRAP.BAS 
movecom \hamcalc64\prog\WHEATSTO.old \hamcalc64\prog\WHEATSTO.BAS 
movecom \hamcalc64\prog\WINCHIL.old \hamcalc64\prog\WINCHIL.BAS 
movecom \hamcalc64\prog\WINDCHIL.old \hamcalc64\prog\WINDCHIL.BAS 
movecom \hamcalc64\prog\WINDING.old \hamcalc64\prog\WINDING.BAS 
movecom \hamcalc64\prog\WINDOM.old \hamcalc64\prog\WINDOM.BAS 
movecom \hamcalc64\prog\WIREANT.old \hamcalc64\prog\WIREANT.BAS 
movecom \hamcalc64\prog\WIRECOND.old \hamcalc64\prog\WIRECOND.BAS 
movecom \hamcalc64\prog\WIREMESH.old \hamcalc64\prog\WIREMESH.BAS 
movecom \hamcalc64\prog\WIREPEOP.old \hamcalc64\prog\WIREPEOP.BAS 
movecom \hamcalc64\prog\WIREPROP.old \hamcalc64\prog\WIREPROP.BAS 
movecom \hamcalc64\prog\WIRESAG.old \hamcalc64\prog\WIRESAG.BAS 
movecom \hamcalc64\prog\WORKS.old \hamcalc64\prog\WORKS.BAS 
movecom \hamcalc64\prog\WX.old \hamcalc64\prog\WX.BAS 
movecom \hamcalc64\prog\XFMR.old \hamcalc64\prog\XFMR.BAS 
movecom \hamcalc64\prog\XFMRNARO.old \hamcalc64\prog\XFMRNARO.BAS 
movecom \hamcalc64\prog\XMTRZMAT.old \hamcalc64\prog\XMTRZMAT.BAS 
movecom \hamcalc64\prog\XOVER.old \hamcalc64\prog\XOVER.BAS 
movecom \hamcalc64\prog\YAGI3EL.old \hamcalc64\prog\YAGI3EL.BAS 
movecom \hamcalc64\prog\YAGILONG.old \hamcalc64\prog\YAGILONG.BAS 
movecom \hamcalc64\prog\YAGISPAC.old \hamcalc64\prog\YAGISPAC.BAS 
movecom \hamcalc64\prog\YAGLONG.old \hamcalc64\prog\YAGLONG.BAS 
movecom \hamcalc64\prog\YAGTAPER.old \hamcalc64\prog\YAGTAPER.BAS 
movecom \hamcalc64\prog\ZENER.old \hamcalc64\prog\ZENER.BAS 
movecom \hamcalc64\prog\ZEPP.old \hamcalc64\prog\ZEPP.BAS 
movecom \hamcalc64\prog\ZEPPDBL.old \hamcalc64\prog\ZEPPDBL.BAS 
movecom \hamcalc64\prog\ZEXIT.old \hamcalc64\prog\ZEXIT.BAS 
movecom \hamcalc64\prog\ZOSTEPUP.old \hamcalc64\prog\ZOSTEPUP.BAS 
movecom \hamcalc64\prog\zounds.old \hamcalc64\prog\zounds.bas 
