rem @echo off 
rem a homemade batch file 
qb64 -c \hamcalc64\prog\DECIFRAC.BAS 
move \qb64\DECIFRAC.exe \hamcalc64\prog\DECIFRAC.exe 
qb64 -c \hamcalc64\prog\DELTAMAT.BAS 
move \qb64\DELTAMAT.exe \hamcalc64\prog\DELTAMAT.exe 
qb64 -c \hamcalc64\prog\DELTLOAD.BAS 
move \qb64\DELTLOAD.exe \hamcalc64\prog\DELTLOAD.exe 
qb64 -c \hamcalc64\prog\DEPREC.BAS 
move \qb64\DEPREC.exe \hamcalc64\prog\DEPREC.exe 
qb64 -c \hamcalc64\prog\DIALGTH.BAS 
move \qb64\DIALGTH.exe \hamcalc64\prog\DIALGTH.exe 
qb64 -c \hamcalc64\prog\DIAMFIND.BAS 
move \qb64\DIAMFIND.exe \hamcalc64\prog\DIAMFIND.exe 
qb64 -c \hamcalc64\prog\DIELECT.BAS 
move \qb64\DIELECT.exe \hamcalc64\prog\DIELECT.exe 
qb64 -c \hamcalc64\prog\DIPOL160.BAS 
move \qb64\DIPOL160.exe \hamcalc64\prog\DIPOL160.exe 
qb64 -c \hamcalc64\prog\DISCONE.BAS 
move \qb64\DISCONE.exe \hamcalc64\prog\DISCONE.exe 
qb64 -c \hamcalc64\prog\DISHANT.BAS 
move \qb64\DISHANT.exe \hamcalc64\prog\DISHANT.exe 
qb64 -c \hamcalc64\prog\DPEEDTD.BAS 
move \qb64\DPEEDTD.exe \hamcalc64\prog\DPEEDTD.exe 
qb64 -c \hamcalc64\prog\DSGNMENU.BAS 
move \qb64\DSGNMENU.exe \hamcalc64\prog\DSGNMENU.exe 
qb64 -c \hamcalc64\prog\DSGNRC.BAS 
move \qb64\DSGNRC.exe \hamcalc64\prog\DSGNRC.exe 
qb64 -c \hamcalc64\prog\DSGNRLC.BAS 
move \qb64\DSGNRLC.exe \hamcalc64\prog\DSGNRLC.exe 
qb64 -c \hamcalc64\prog\DUOPOLE.BAS 
move \qb64\DUOPOLE.exe \hamcalc64\prog\DUOPOLE.exe 
qb64 -c \hamcalc64\prog\DUOPWR.BAS 
move \qb64\DUOPWR.exe \hamcalc64\prog\DUOPWR.exe 
qb64 -c \hamcalc64\prog\ELECLENG.BAS 
move \qb64\ELECLENG.exe \hamcalc64\prog\ELECLENG.exe 
qb64 -c \hamcalc64\prog\ELECOST.BAS 
move \qb64\ELECOST.exe \hamcalc64\prog\ELECOST.exe 
qb64 -c \hamcalc64\prog\ELFLASH.BAS 
move \qb64\ELFLASH.exe \hamcalc64\prog\ELFLASH.exe 
qb64 -c \hamcalc64\prog\ELSPEC.BAS 
move \qb64\ELSPEC.exe \hamcalc64\prog\ELSPEC.exe 
qb64 -c \hamcalc64\prog\EQUIV.BAS 
move \qb64\EQUIV.exe \hamcalc64\prog\EQUIV.exe 
qb64 -c \hamcalc64\prog\ES2B.BAS 
move \qb64\ES2B.exe \hamcalc64\prog\ES2B.exe 
qb64 -c \hamcalc64\prog\EXIT.BAS 
move \qb64\EXIT.exe \hamcalc64\prog\EXIT.exe 
qb64 -c \hamcalc64\prog\EXPOSURE.BAS 
move \qb64\EXPOSURE.exe \hamcalc64\prog\EXPOSURE.exe 
qb64 -c \hamcalc64\prog\FATDIPOL.BAS 
move \qb64\FATDIPOL.exe \hamcalc64\prog\FATDIPOL.exe 
qb64 -c \hamcalc64\prog\FIBON.BAS 
move \qb64\FIBON.exe \hamcalc64\prog\FIBON.exe 
qb64 -c \hamcalc64\prog\FILSTRIP.BAS 
move \qb64\FILSTRIP.exe \hamcalc64\prog\FILSTRIP.exe 
qb64 -c \hamcalc64\prog\FILTER.BAS 
move \qb64\FILTER.exe \hamcalc64\prog\FILTER.exe 
qb64 -c \hamcalc64\prog\FILTRLC.BAS 
move \qb64\FILTRLC.exe \hamcalc64\prog\FILTRLC.exe 
qb64 -c \hamcalc64\prog\FILTUT.BAS 
move \qb64\FILTUT.exe \hamcalc64\prog\FILTUT.exe 
qb64 -c \hamcalc64\prog\FINANCE.BAS 
move \qb64\FINANCE.exe \hamcalc64\prog\FINANCE.exe 
qb64 -c \hamcalc64\prog\FISHBONE.BAS 
move \qb64\FISHBONE.exe \hamcalc64\prog\FISHBONE.exe 
qb64 -c \hamcalc64\prog\FOCUS.BAS 
move \qb64\FOCUS.exe \hamcalc64\prog\FOCUS.exe 
qb64 -c \hamcalc64\prog\FOLDIPOL.BAS 
move \qb64\FOLDIPOL.exe \hamcalc64\prog\FOLDIPOL.exe 
qb64 -c \hamcalc64\prog\FORMULAE.BAS 
move \qb64\FORMULAE.exe \hamcalc64\prog\FORMULAE.exe 
qb64 -c \hamcalc64\prog\FOROMENU.BAS 
move \qb64\FOROMENU.exe \hamcalc64\prog\FOROMENU.exe 
qb64 -c \hamcalc64\prog\FOTOCOPY.BAS 
move \qb64\FOTOCOPY.exe \hamcalc64\prog\FOTOCOPY.exe 
qb64 -c \hamcalc64\prog\FOTOMENU.BAS 
move \qb64\FOTOMENU.exe \hamcalc64\prog\FOTOMENU.exe 
qb64 -c \hamcalc64\prog\FOTOMOVE.BAS 
move \qb64\FOTOMOVE.exe \hamcalc64\prog\FOTOMOVE.exe 
qb64 -c \hamcalc64\prog\FOXLOG.BAS 
move \qb64\FOXLOG.exe \hamcalc64\prog\FOXLOG.exe 
qb64 -c \hamcalc64\prog\FUSEWIRE.BAS 
move \qb64\FUSEWIRE.exe \hamcalc64\prog\FUSEWIRE.exe 
qb64 -c \hamcalc64\prog\G5RV.BAS 
move \qb64\G5RV.exe \hamcalc64\prog\G5RV.exe 
qb64 -c \hamcalc64\prog\GAMMATCH.BAS 
move \qb64\GAMMATCH.exe \hamcalc64\prog\GAMMATCH.exe 
qb64 -c \hamcalc64\prog\GAPLOT.BAS 
move \qb64\GAPLOT.exe \hamcalc64\prog\GAPLOT.exe 
qb64 -c \hamcalc64\prog\GEARING.BAS 
move \qb64\GEARING.exe \hamcalc64\prog\GEARING.exe 
qb64 -c \hamcalc64\prog\GRAPHS.BAS 
move \qb64\GRAPHS.exe \hamcalc64\prog\GRAPHS.exe 
qb64 -c \hamcalc64\prog\GRIDSQ.BAS 
move \qb64\GRIDSQ.exe \hamcalc64\prog\GRIDSQ.exe 
qb64 -c \hamcalc64\prog\GUYWIRES.BAS 
move \qb64\GUYWIRES.exe \hamcalc64\prog\GUYWIRES.exe 
qb64 -c \hamcalc64\prog\HAIRPIN.BAS 
move \qb64\HAIRPIN.exe \hamcalc64\prog\HAIRPIN.exe 
qb64 -c \hamcalc64\prog\HALFLOOP.BAS 
move \qb64\HALFLOOP.exe \hamcalc64\prog\HALFLOOP.exe 
qb64 -c \hamcalc64\prog\HAMBANDS.BAS 
move \qb64\HAMBANDS.exe \hamcalc64\prog\HAMBANDS.exe 
qb64 -c \hamcalc64\prog\HAMCALC.BAS 
move \qb64\HAMCALC.exe \hamcalc64\prog\HAMCALC.exe 
qb64 -c \hamcalc64\prog\HAMDEX.BAS 
move \qb64\HAMDEX.exe \hamcalc64\prog\HAMDEX.exe 
qb64 -c \hamcalc64\prog\HARMONIC.BAS 
move \qb64\HARMONIC.exe \hamcalc64\prog\HARMONIC.exe 
qb64 -c \hamcalc64\prog\HARTOSC.BAS 
move \qb64\HARTOSC.exe \hamcalc64\prog\HARTOSC.exe 
qb64 -c \hamcalc64\prog\HARTOSC3.BAS 
move \qb64\HARTOSC3.exe \hamcalc64\prog\HARTOSC3.exe 
qb64 -c \hamcalc64\prog\HATSHAPE.BAS 
move \qb64\HATSHAPE.exe \hamcalc64\prog\HATSHAPE.exe 
qb64 -c \hamcalc64\prog\HCAL-X.BAS 
move \qb64\HCAL-X.exe \hamcalc64\prog\HCAL-X.exe 
qb64 -c \hamcalc64\prog\HCAL.BAS 
move \qb64\HCAL.exe \hamcalc64\prog\HCAL.exe 
qb64 -c \hamcalc64\prog\HELANT.BAS 
move \qb64\HELANT.exe \hamcalc64\prog\HELANT.exe 
qb64 -c \hamcalc64\prog\HELIX.BAS 
move \qb64\HELIX.exe \hamcalc64\prog\HELIX.exe 
qb64 -c \hamcalc64\prog\HELPHINT.BAS 
move \qb64\HELPHINT.exe \hamcalc64\prog\HELPHINT.exe 
qb64 -c \hamcalc64\prog\HELRESON.BAS 
move \qb64\HELRESON.exe \hamcalc64\prog\HELRESON.exe 
qb64 -c \hamcalc64\prog\HELVERT.BAS 
move \qb64\HELVERT.exe \hamcalc64\prog\HELVERT.exe 
qb64 -c \hamcalc64\prog\HOTBOX.BAS 
move \qb64\HOTBOX.exe \hamcalc64\prog\HOTBOX.exe 
qb64 -c \hamcalc64\prog\HUMID.BAS 
move \qb64\HUMID.exe \hamcalc64\prog\HUMID.exe 
qb64 -c \hamcalc64\prog\HXINSTAL.BAS 
move \qb64\HXINSTAL.exe \hamcalc64\prog\HXINSTAL.exe 
qb64 -c \hamcalc64\prog\IMPANT.BAS 
move \qb64\IMPANT.exe \hamcalc64\prog\IMPANT.exe 
qb64 -c \hamcalc64\prog\IMPARES.BAS 
move \qb64\IMPARES.exe \hamcalc64\prog\IMPARES.exe 
qb64 -c \hamcalc64\prog\IMPEDCCT.BAS 
move \qb64\IMPEDCCT.exe \hamcalc64\prog\IMPEDCCT.exe 
qb64 -c \hamcalc64\prog\IMPEDMET.BAS 
move \qb64\IMPEDMET.exe \hamcalc64\prog\IMPEDMET.exe 
qb64 -c \hamcalc64\prog\IMPEDNET.BAS 
move \qb64\IMPEDNET.exe \hamcalc64\prog\IMPEDNET.exe 
qb64 -c \hamcalc64\prog\INDUCALC.BAS 
move \qb64\INDUCALC.exe \hamcalc64\prog\INDUCALC.exe 
qb64 -c \hamcalc64\prog\INDUHOSE.BAS 
move \qb64\INDUHOSE.exe \hamcalc64\prog\INDUHOSE.exe 
qb64 -c \hamcalc64\prog\INDULOOP.BAS 
move \qb64\INDULOOP.exe \hamcalc64\prog\INDULOOP.exe 
qb64 -c \hamcalc64\prog\INLOSS.BAS 
move \qb64\INLOSS.exe \hamcalc64\prog\INLOSS.exe 
qb64 -c \hamcalc64\prog\INSERLOS.BAS 
move \qb64\INSERLOS.exe \hamcalc64\prog\INSERLOS.exe 
qb64 -c \hamcalc64\prog\INTRO.BAS 
move \qb64\INTRO.exe \hamcalc64\prog\INTRO.exe 
qb64 -c \hamcalc64\prog\INVEE.BAS 
move \qb64\INVEE.exe \hamcalc64\prog\INVEE.exe 
qb64 -c \hamcalc64\prog\INVOLUTE.BAS 
move \qb64\INVOLUTE.exe \hamcalc64\prog\INVOLUTE.exe 
qb64 -c \hamcalc64\prog\JAYPOLE.BAS 
move \qb64\JAYPOLE.exe \hamcalc64\prog\JAYPOLE.exe 
qb64 -c \hamcalc64\prog\JCALC.BAS 
move \qb64\JCALC.exe \hamcalc64\prog\JCALC.exe 
qb64 -c \hamcalc64\prog\KFACTOR.BAS 
move \qb64\KFACTOR.exe \hamcalc64\prog\KFACTOR.exe 
qb64 -c \hamcalc64\prog\L-PAD.BAS 
move \qb64\L-PAD.exe \hamcalc64\prog\L-PAD.exe 
qb64 -c \hamcalc64\prog\LADANT.BAS 
move \qb64\LADANT.exe \hamcalc64\prog\LADANT.exe 
qb64 -c \hamcalc64\prog\LADDER2.BAS 
move \qb64\LADDER2.exe \hamcalc64\prog\LADDER2.exe 
qb64 -c \hamcalc64\prog\LADRSOLV.BAS 
move \qb64\LADRSOLV.exe \hamcalc64\prog\LADRSOLV.exe 
qb64 -c \hamcalc64\prog\LAMPLIFE.BAS 
move \qb64\LAMPLIFE.exe \hamcalc64\prog\LAMPLIFE.exe 
qb64 -c \hamcalc64\prog\LATLONG.BAS 
move \qb64\LATLONG.exe \hamcalc64\prog\LATLONG.exe 
qb64 -c \hamcalc64\prog\LED.BAS 
move \qb64\LED.exe \hamcalc64\prog\LED.exe 
qb64 -c \hamcalc64\prog\LENSES.BAS 
move \qb64\LENSES.exe \hamcalc64\prog\LENSES.exe 
qb64 -c \hamcalc64\prog\LENSRING.BAS 
move \qb64\LENSRING.exe \hamcalc64\prog\LENSRING.exe 
qb64 -c \hamcalc64\prog\LINELOSS.BAS 
move \qb64\LINELOSS.exe \hamcalc64\prog\LINELOSS.exe 
qb64 -c \hamcalc64\prog\LINKUPL.BAS 
move \qb64\LINKUPL.exe \hamcalc64\prog\LINKUPL.exe 
qb64 -c \hamcalc64\prog\LIST10.BAS 
move \qb64\LIST10.exe \hamcalc64\prog\LIST10.exe 
qb64 -c \hamcalc64\prog\LM17.BAS 
move \qb64\LM17.exe \hamcalc64\prog\LM17.exe 
qb64 -c \hamcalc64\prog\LM315.BAS 
move \qb64\LM315.exe \hamcalc64\prog\LM315.exe 
qb64 -c \hamcalc64\prog\LM317.BAS 
move \qb64\LM317.exe \hamcalc64\prog\LM317.exe 
qb64 -c \hamcalc64\prog\LM317RUN.BAS 
move \qb64\LM317RUN.exe \hamcalc64\prog\LM317RUN.exe 
qb64 -c \hamcalc64\prog\LOANPAY.BAS 
move \qb64\LOANPAY.exe \hamcalc64\prog\LOANPAY.exe 
qb64 -c \hamcalc64\prog\LOCALRPT.BAS 
move \qb64\LOCALRPT.exe \hamcalc64\prog\LOCALRPT.exe 
qb64 -c \hamcalc64\prog\LOGOCLOK.BAS 
move \qb64\LOGOCLOK.exe \hamcalc64\prog\LOGOCLOK.exe 
qb64 -c \hamcalc64\prog\LOGYAG.BAS 
move \qb64\LOGYAG.exe \hamcalc64\prog\LOGYAG.exe 
qb64 -c \hamcalc64\prog\LOOPANT.BAS 
move \qb64\LOOPANT.exe \hamcalc64\prog\LOOPANT.exe 
qb64 -c \hamcalc64\prog\LOOPSKY.BAS 
move \qb64\LOOPSKY.exe \hamcalc64\prog\LOOPSKY.exe 
qb64 -c \hamcalc64\prog\LOOPXMIT.BAS 
move \qb64\LOOPXMIT.exe \hamcalc64\prog\LOOPXMIT.exe 
qb64 -c \hamcalc64\prog\LOPASS.BAS 
move \qb64\LOPASS.exe \hamcalc64\prog\LOPASS.exe 
qb64 -c \hamcalc64\prog\LOSSY.BAS 
move \qb64\LOSSY.exe \hamcalc64\prog\LOSSY.exe 
qb64 -c \hamcalc64\prog\LPTSETUP.BAS 
move \qb64\LPTSETUP.exe \hamcalc64\prog\LPTSETUP.exe 
qb64 -c \hamcalc64\prog\MATCHBOX.BAS 
move \qb64\MATCHBOX.exe \hamcalc64\prog\MATCHBOX.exe 
qb64 -c \hamcalc64\prog\MATCHNET.BAS 
move \qb64\MATCHNET.exe \hamcalc64\prog\MATCHNET.exe 
qb64 -c \hamcalc64\prog\MATFILT.BAS 
move \qb64\MATFILT.exe \hamcalc64\prog\MATFILT.exe 
qb64 -c \hamcalc64\prog\MATRICS.BAS 
move \qb64\MATRICS.exe \hamcalc64\prog\MATRICS.exe 
qb64 -c \hamcalc64\prog\MAXUF.BAS 
move \qb64\MAXUF.exe \hamcalc64\prog\MAXUF.exe 
qb64 -c \hamcalc64\prog\MECHMENU.BAS 
move \qb64\MECHMENU.exe \hamcalc64\prog\MECHMENU.exe 
qb64 -c \hamcalc64\prog\METERS.BAS 
move \qb64\METERS.exe \hamcalc64\prog\METERS.exe 
qb64 -c \hamcalc64\prog\METNOM.BAS 
move \qb64\METNOM.exe \hamcalc64\prog\METNOM.exe 
qb64 -c \hamcalc64\prog\METRICS.BAS 
move \qb64\METRICS.exe \hamcalc64\prog\METRICS.exe 
qb64 -c \hamcalc64\prog\METSHOWR.BAS 
move \qb64\METSHOWR.exe \hamcalc64\prog\METSHOWR.exe 
qb64 -c \hamcalc64\prog\MICLOOP.BAS 
move \qb64\MICLOOP.exe \hamcalc64\prog\MICLOOP.exe 
qb64 -c \hamcalc64\prog\MICROVER.BAS 
move \qb64\MICROVER.exe \hamcalc64\prog\MICROVER.exe 
qb64 -c \hamcalc64\prog\MINILOOP.BAS 
move \qb64\MINILOOP.exe \hamcalc64\prog\MINILOOP.exe 
qb64 -c \hamcalc64\prog\MINIQUAD.BAS 
move \qb64\MINIQUAD.exe \hamcalc64\prog\MINIQUAD.exe 
qb64 -c \hamcalc64\prog\MISMAT.BAS 
move \qb64\MISMAT.exe \hamcalc64\prog\MISMAT.exe 
qb64 -c \hamcalc64\prog\MIWHIP.BAS 
move \qb64\MIWHIP.exe \hamcalc64\prog\MIWHIP.exe 
qb64 -c \hamcalc64\prog\MOBILMAT.BAS 
move \qb64\MOBILMAT.exe \hamcalc64\prog\MOBILMAT.exe 
qb64 -c \hamcalc64\prog\MOONTRAC.BAS 
move \qb64\MOONTRAC.exe \hamcalc64\prog\MOONTRAC.exe 
qb64 -c \hamcalc64\prog\MORTGAG.BAS 
move \qb64\MORTGAG.exe \hamcalc64\prog\MORTGAG.exe 
qb64 -c \hamcalc64\prog\MOWHIP.BAS 
move \qb64\MOWHIP.exe \hamcalc64\prog\MOWHIP.exe 
qb64 -c \hamcalc64\prog\MOXON.BAS 
move \qb64\MOXON.exe \hamcalc64\prog\MOXON.exe 
qb64 -c \hamcalc64\prog\NEWSINCE.BAS 
move \qb64\NEWSINCE.exe \hamcalc64\prog\NEWSINCE.exe 
qb64 -c \hamcalc64\prog\NICAD.BAS 
move \qb64\NICAD.exe \hamcalc64\prog\NICAD.exe 
qb64 -c \hamcalc64\prog\NMBRSIZE.BAS 
move \qb64\NMBRSIZE.exe \hamcalc64\prog\NMBRSIZE.exe 
qb64 -c \hamcalc64\prog\NODE.BAS 
move \qb64\NODE.exe \hamcalc64\prog\NODE.exe 
qb64 -c \hamcalc64\prog\NOISFIG.BAS 
move \qb64\NOISFIG.exe \hamcalc64\prog\NOISFIG.exe 
qb64 -c \hamcalc64\prog\NOLOSS.BAS 
move \qb64\NOLOSS.exe \hamcalc64\prog\NOLOSS.exe 
qb64 -c \hamcalc64\prog\NUMDERIV.BAS 
move \qb64\NUMDERIV.exe \hamcalc64\prog\NUMDERIV.exe 
qb64 -c \hamcalc64\prog\NUMSORT.BAS 
move \qb64\NUMSORT.exe \hamcalc64\prog\NUMSORT.exe 
qb64 -c \hamcalc64\prog\OCFDIPOL.BAS 
move \qb64\OCFDIPOL.exe \hamcalc64\prog\OCFDIPOL.exe 
qb64 -c \hamcalc64\prog\OCTAGON.BAS 
move \qb64\OCTAGON.exe \hamcalc64\prog\OCTAGON.exe 
qb64 -c \hamcalc64\prog\OCTALOOP.BAS 
move \qb64\OCTALOOP.exe \hamcalc64\prog\OCTALOOP.exe 
qb64 -c \hamcalc64\prog\OCTARING.BAS 
move \qb64\OCTARING.exe \hamcalc64\prog\OCTARING.exe 
qb64 -c \hamcalc64\prog\OHMSLAW.BAS 
move \qb64\OHMSLAW.exe \hamcalc64\prog\OHMSLAW.exe 
qb64 -c \hamcalc64\prog\OPAMP.BAS 
move \qb64\OPAMP.exe \hamcalc64\prog\OPAMP.exe 
qb64 -c \hamcalc64\prog\OPENWIRE.BAS 
move \qb64\OPENWIRE.exe \hamcalc64\prog\OPENWIRE.exe 
qb64 -c \hamcalc64\prog\PAGE437.BAS 
move \qb64\PAGE437.exe \hamcalc64\prog\PAGE437.exe 
qb64 -c \hamcalc64\prog\PAIRLT.BAS 
move \qb64\PAIRLT.exe \hamcalc64\prog\PAIRLT.exe 
qb64 -c \hamcalc64\prog\PATHFIND.BAS 
move \qb64\PATHFIND.exe \hamcalc64\prog\PATHFIND.exe 
qb64 -c \hamcalc64\prog\PBA.BAS 
move \qb64\PBA.exe \hamcalc64\prog\PBA.exe 
qb64 -c \hamcalc64\prog\PEDOM.BAS 
move \qb64\PEDOM.exe \hamcalc64\prog\PEDOM.exe 
qb64 -c \hamcalc64\prog\PHAZDIFF.BAS 
move \qb64\PHAZDIFF.exe \hamcalc64\prog\PHAZDIFF.exe 
qb64 -c \hamcalc64\prog\PIMATCH.BAS 
move \qb64\PIMATCH.exe \hamcalc64\prog\PIMATCH.exe 
qb64 -c \hamcalc64\prog\PIPESIZE.BAS 
move \qb64\PIPESIZE.exe \hamcalc64\prog\PIPESIZE.exe 
qb64 -c \hamcalc64\prog\PITNET.BAS 
move \qb64\PITNET.exe \hamcalc64\prog\PITNET.exe 
qb64 -c \hamcalc64\prog\PIXEL.BAS 
move \qb64\PIXEL.exe \hamcalc64\prog\PIXEL.exe 
qb64 -c \hamcalc64\prog\POLYGON.BAS 
move \qb64\POLYGON.exe \hamcalc64\prog\POLYGON.exe 
qb64 -c \hamcalc64\prog\POTENT.BAS 
move \qb64\POTENT.exe \hamcalc64\prog\POTENT.exe 
qb64 -c \hamcalc64\prog\POWRXFMR.BAS 
move \qb64\POWRXFMR.exe \hamcalc64\prog\POWRXFMR.exe 
qb64 -c \hamcalc64\prog\PRACOSC.BAS 
move \qb64\PRACOSC.exe \hamcalc64\prog\PRACOSC.exe 
qb64 -c \hamcalc64\prog\PRECICAP.BAS 
move \qb64\PRECICAP.exe \hamcalc64\prog\PRECICAP.exe 
qb64 -c \hamcalc64\prog\PRECIRES.BAS 
move \qb64\PRECIRES.exe \hamcalc64\prog\PRECIRES.exe 
qb64 -c \hamcalc64\prog\PRIMENOS.BAS 
move \qb64\PRIMENOS.exe \hamcalc64\prog\PRIMENOS.exe 
qb64 -c \hamcalc64\prog\PRINTIP.BAS 
move \qb64\PRINTIP.exe \hamcalc64\prog\PRINTIP.exe 
qb64 -c \hamcalc64\prog\PROPCIRC.BAS 
move \qb64\PROPCIRC.exe \hamcalc64\prog\PROPCIRC.exe 
qb64 -c \hamcalc64\prog\PRT.BAS 
move \qb64\PRT.exe \hamcalc64\prog\PRT.exe 
qb64 -c \hamcalc64\prog\PSUP.BAS 
move \qb64\PSUP.exe \hamcalc64\prog\PSUP.exe 
qb64 -c \hamcalc64\prog\PSUPERF.BAS 
move \qb64\PSUPERF.exe \hamcalc64\prog\PSUPERF.exe 
qb64 -c \hamcalc64\prog\PSYCHROM.BAS 
move \qb64\PSYCHROM.exe \hamcalc64\prog\PSYCHROM.exe 
qb64 -c \hamcalc64\prog\PULSEGEN.BAS 
move \qb64\PULSEGEN.exe \hamcalc64\prog\PULSEGEN.exe 
qb64 -c \hamcalc64\prog\PWRCCT.BAS 
move \qb64\PWRCCT.exe \hamcalc64\prog\PWRCCT.exe 
qb64 -c \hamcalc64\prog\PWRDIV.BAS 
move \qb64\PWRDIV.exe \hamcalc64\prog\PWRDIV.exe 
qb64 -c \hamcalc64\prog\PWRSUPP.BAS 
move \qb64\PWRSUPP.exe \hamcalc64\prog\PWRSUPP.exe 
qb64 -c \hamcalc64\prog\PWRXFMR.BAS 
move \qb64\PWRXFMR.exe \hamcalc64\prog\PWRXFMR.exe 
qb64 -c \hamcalc64\prog\Q.BAS 
move \qb64\Q.exe \hamcalc64\prog\Q.exe 
qb64 -c \hamcalc64\prog\QFACTOR.BAS 
move \qb64\QFACTOR.exe \hamcalc64\prog\QFACTOR.exe 
qb64 -c \hamcalc64\prog\QFIND.BAS 
move \qb64\QFIND.exe \hamcalc64\prog\QFIND.exe 
qb64 -c \hamcalc64\prog\QFIND5.BAS 
move \qb64\QFIND5.exe \hamcalc64\prog\QFIND5.exe 
qb64 -c \hamcalc64\prog\QLINE2.BAS 
move \qb64\QLINE2.exe \hamcalc64\prog\QLINE2.exe 
qb64 -c \hamcalc64\prog\QNTIMP.BAS 
move \qb64\QNTIMP.exe \hamcalc64\prog\QNTIMP.exe 
qb64 -c \hamcalc64\prog\QRESON.BAS 
move \qb64\QRESON.exe \hamcalc64\prog\QRESON.exe 
qb64 -c \hamcalc64\prog\QSK.BAS 
move \qb64\QSK.exe \hamcalc64\prog\QSK.exe 
qb64 -c \hamcalc64\prog\QTRAP.BAS 
move \qb64\QTRAP.exe \hamcalc64\prog\QTRAP.exe 
qb64 -c \hamcalc64\prog\QTRAPRUN.BAS 
move \qb64\QTRAPRUN.exe \hamcalc64\prog\QTRAPRUN.exe 
qb64 -c \hamcalc64\prog\QUAD.BAS 
move \qb64\QUAD.exe \hamcalc64\prog\QUAD.exe 
qb64 -c \hamcalc64\prog\QUADRAT.BAS 
move \qb64\QUADRAT.exe \hamcalc64\prog\QUADRAT.exe 
qb64 -c \hamcalc64\prog\QUARTWAV.BAS 
move \qb64\QUARTWAV.exe \hamcalc64\prog\QUARTWAV.exe 
qb64 -c \hamcalc64\prog\QUIKTABL.BAS 
move \qb64\QUIKTABL.exe \hamcalc64\prog\QUIKTABL.exe 
qb64 -c \hamcalc64\prog\RADANGLE.BAS 
move \qb64\RADANGLE.exe \hamcalc64\prog\RADANGLE.exe 
qb64 -c \hamcalc64\prog\RADIOLOS.BAS 
move \qb64\RADIOLOS.exe \hamcalc64\prog\RADIOLOS.exe 
qb64 -c \hamcalc64\prog\RANDNUM.BAS 
move \qb64\RANDNUM.exe \hamcalc64\prog\RANDNUM.exe 
qb64 -c \hamcalc64\prog\RCCONST.BAS 
move \qb64\RCCONST.exe \hamcalc64\prog\RCCONST.exe 
qb64 -c \hamcalc64\prog\RCFILT.BAS 
move \qb64\RCFILT.exe \hamcalc64\prog\RCFILT.exe 
qb64 -c \hamcalc64\prog\RCLOAD2.BAS 
move \qb64\RCLOAD2.exe \hamcalc64\prog\RCLOAD2.exe 
qb64 -c \hamcalc64\prog\REACT.BAS 
move \qb64\REACT.exe \hamcalc64\prog\REACT.exe 
qb64 -c \hamcalc64\prog\REMIND.BAS 
move \qb64\REMIND.exe \hamcalc64\prog\REMIND.exe 
qb64 -c \hamcalc64\prog\REMSIG.BAS 
move \qb64\REMSIG.exe \hamcalc64\prog\REMSIG.exe 
qb64 -c \hamcalc64\prog\RESICOP.BAS 
move \qb64\RESICOP.exe \hamcalc64\prog\RESICOP.exe 
qb64 -c \hamcalc64\prog\RESISTIV.BAS 
move \qb64\RESISTIV.exe \hamcalc64\prog\RESISTIV.exe 
qb64 -c \hamcalc64\prog\RESISVAL.BAS 
move \qb64\RESISVAL.exe \hamcalc64\prog\RESISVAL.exe 
qb64 -c \hamcalc64\prog\RIPPLE.BAS 
move \qb64\RIPPLE.exe \hamcalc64\prog\RIPPLE.exe 
qb64 -c \hamcalc64\prog\RISESET.BAS 
move \qb64\RISESET.exe \hamcalc64\prog\RISESET.exe 
qb64 -c \hamcalc64\prog\RJD.BAS 
move \qb64\RJD.exe \hamcalc64\prog\RJD.exe 
qb64 -c \hamcalc64\prog\ROTAPLOT.BAS 
move \qb64\ROTAPLOT.exe \hamcalc64\prog\ROTAPLOT.exe 
qb64 -c \hamcalc64\prog\RUN.BAS 
move \qb64\RUN.exe \hamcalc64\prog\RUN.exe 
qb64 -c \hamcalc64\prog\SATORBIT.BAS 
move \qb64\SATORBIT.exe \hamcalc64\prog\SATORBIT.exe 
qb64 -c \hamcalc64\prog\SCALSPD.BAS 
move \qb64\SCALSPD.exe \hamcalc64\prog\SCALSPD.exe 
qb64 -c \hamcalc64\prog\SCHMIDT.BAS 
move \qb64\SCHMIDT.exe \hamcalc64\prog\SCHMIDT.exe 
qb64 -c \hamcalc64\prog\SEASONS.BAS 
move \qb64\SEASONS.exe \hamcalc64\prog\SEASONS.exe 
qb64 -c \hamcalc64\prog\SEPAQ.BAS 
move \qb64\SEPAQ.exe \hamcalc64\prog\SEPAQ.exe 
qb64 -c \hamcalc64\prog\SERISECT.BAS 
move \qb64\SERISECT.exe \hamcalc64\prog\SERISECT.exe 
qb64 -c \hamcalc64\prog\SERPAR-Q.BAS 
move \qb64\SERPAR-Q.exe \hamcalc64\prog\SERPAR-Q.exe 
qb64 -c \hamcalc64\prog\SERSECT.BAS 
move \qb64\SERSECT.exe \hamcalc64\prog\SERSECT.exe 
qb64 -c \hamcalc64\prog\SHAFT.BAS 
move \qb64\SHAFT.exe \hamcalc64\prog\SHAFT.exe 
qb64 -c \hamcalc64\prog\SHORTANT.BAS 
move \qb64\SHORTANT.exe \hamcalc64\prog\SHORTANT.exe 
qb64 -c \hamcalc64\prog\SHORTDIP.BAS 
move \qb64\SHORTDIP.exe \hamcalc64\prog\SHORTDIP.exe 
qb64 -c \hamcalc64\prog\SHUTTLE.BAS 
move \qb64\SHUTTLE.exe \hamcalc64\prog\SHUTTLE.exe 
qb64 -c \hamcalc64\prog\SIMULEQ.BAS 
move \qb64\SIMULEQ.exe \hamcalc64\prog\SIMULEQ.exe 
qb64 -c \hamcalc64\prog\SINK.BAS 
move \qb64\SINK.exe \hamcalc64\prog\SINK.exe 
qb64 -c \hamcalc64\prog\SKIPDIST.BAS 
move \qb64\SKIPDIST.exe \hamcalc64\prog\SKIPDIST.exe 
qb64 -c \hamcalc64\prog\SLOPER.BAS 
move \qb64\SLOPER.exe \hamcalc64\prog\SLOPER.exe 
qb64 -c \hamcalc64\prog\SMETER.BAS 
move \qb64\SMETER.exe \hamcalc64\prog\SMETER.exe 
qb64 -c \hamcalc64\prog\SMITHCHT.BAS 
move \qb64\SMITHCHT.exe \hamcalc64\prog\SMITHCHT.exe 
qb64 -c \hamcalc64\prog\SNGLWIRE.BAS 
move \qb64\SNGLWIRE.exe \hamcalc64\prog\SNGLWIRE.exe 
qb64 -c \hamcalc64\prog\SOLUTRI.BAS 
move \qb64\SOLUTRI.exe \hamcalc64\prog\SOLUTRI.exe 
qb64 -c \hamcalc64\prog\SORTER.BAS 
move \qb64\SORTER.exe \hamcalc64\prog\SORTER.exe 
qb64 -c \hamcalc64\prog\SPARK.BAS 
move \qb64\SPARK.exe \hamcalc64\prog\SPARK.exe 
qb64 -c \hamcalc64\prog\SPEAKR.BAS 
move \qb64\SPEAKR.exe \hamcalc64\prog\SPEAKR.exe 
qb64 -c \hamcalc64\prog\SPEEDTD.BAS 
move \qb64\SPEEDTD.exe \hamcalc64\prog\SPEEDTD.exe 
qb64 -c \hamcalc64\prog\SQCOAX.BAS 
move \qb64\SQCOAX.exe \hamcalc64\prog\SQCOAX.exe 
qb64 -c \hamcalc64\prog\SQLINE.BAS 
move \qb64\SQLINE.exe \hamcalc64\prog\SQLINE.exe 
qb64 -c \hamcalc64\prog\STAIRS.BAS 
move \qb64\STAIRS.exe \hamcalc64\prog\STAIRS.exe 
qb64 -c \hamcalc64\prog\STUBANT.BAS 
move \qb64\STUBANT.exe \hamcalc64\prog\STUBANT.exe 
qb64 -c \hamcalc64\prog\SUNUP.BAS 
move \qb64\SUNUP.exe \hamcalc64\prog\SUNUP.exe 
qb64 -c \hamcalc64\prog\SURVEY.BAS 
move \qb64\SURVEY.exe \hamcalc64\prog\SURVEY.exe 
qb64 -c \hamcalc64\prog\SWR.BAS 
move \qb64\SWR.exe \hamcalc64\prog\SWR.exe 
qb64 -c \hamcalc64\prog\T2FD.BAS 
move \qb64\T2FD.exe \hamcalc64\prog\T2FD.exe 
qb64 -c \hamcalc64\prog\TANKCCT.BAS 
move \qb64\TANKCCT.exe \hamcalc64\prog\TANKCCT.exe 
qb64 -c \hamcalc64\prog\TEEMATCH.BAS 
move \qb64\TEEMATCH.exe \hamcalc64\prog\TEEMATCH.exe 
qb64 -c \hamcalc64\prog\TELETUBE.BAS 
move \qb64\TELETUBE.exe \hamcalc64\prog\TELETUBE.exe 
qb64 -c \hamcalc64\prog\TEST.BAS 
move \qb64\TEST.exe \hamcalc64\prog\TEST.exe 
qb64 -c \hamcalc64\prog\TFORM3.BAS 
move \qb64\TFORM3.exe \hamcalc64\prog\TFORM3.exe 
qb64 -c \hamcalc64\prog\THERMRES.BAS 
move \qb64\THERMRES.exe \hamcalc64\prog\THERMRES.exe 
qb64 -c \hamcalc64\prog\THEVININ.BAS 
move \qb64\THEVININ.exe \hamcalc64\prog\THEVININ.exe 
qb64 -c \hamcalc64\prog\THRUBOOM.BAS 
move \qb64\THRUBOOM.exe \hamcalc64\prog\THRUBOOM.exe 
qb64 -c \hamcalc64\prog\TIMEQ.BAS 
move \qb64\TIMEQ.exe \hamcalc64\prog\TIMEQ.exe 
qb64 -c \hamcalc64\prog\TIMEZONE.BAS 
move \qb64\TIMEZONE.exe \hamcalc64\prog\TIMEZONE.exe 
qb64 -c \hamcalc64\prog\TINYCOIL.BAS 
move \qb64\TINYCOIL.exe \hamcalc64\prog\TINYCOIL.exe 
qb64 -c \hamcalc64\prog\TITLER.BAS 
move \qb64\TITLER.exe \hamcalc64\prog\TITLER.exe 
qb64 -c \hamcalc64\prog\TJD.BAS 
move \qb64\TJD.exe \hamcalc64\prog\TJD.exe 
qb64 -c \hamcalc64\prog\TMATCH.BAS 
move \qb64\TMATCH.exe \hamcalc64\prog\TMATCH.exe 
qb64 -c \hamcalc64\prog\TOROID.BAS 
move \qb64\TOROID.exe \hamcalc64\prog\TOROID.exe 
qb64 -c \hamcalc64\prog\TOROTRAP.BAS 
move \qb64\TOROTRAP.exe \hamcalc64\prog\TOROTRAP.exe 
qb64 -c \hamcalc64\prog\TORQUE.BAS 
move \qb64\TORQUE.exe \hamcalc64\prog\TORQUE.exe 
qb64 -c \hamcalc64\prog\TRACKER.BAS 
move \qb64\TRACKER.exe \hamcalc64\prog\TRACKER.exe 
qb64 -c \hamcalc64\prog\TRANCCT.BAS 
move \qb64\TRANCCT.exe \hamcalc64\prog\TRANCCT.exe 
qb64 -c \hamcalc64\prog\TRANLINE.BAS 
move \qb64\TRANLINE.exe \hamcalc64\prog\TRANLINE.exe 
qb64 -c \hamcalc64\prog\TRANSMAT.BAS 
move \qb64\TRANSMAT.exe \hamcalc64\prog\TRANSMAT.exe 
qb64 -c \hamcalc64\prog\TRANSTUB.BAS 
move \qb64\TRANSTUB.exe \hamcalc64\prog\TRANSTUB.exe 
qb64 -c \hamcalc64\prog\TRAPCALC.BAS 
move \qb64\TRAPCALC.exe \hamcalc64\prog\TRAPCALC.exe 
qb64 -c \hamcalc64\prog\TRAPDSGN.BAS 
move \qb64\TRAPDSGN.exe \hamcalc64\prog\TRAPDSGN.exe 
qb64 -c \hamcalc64\prog\TRAPOLE.BAS 
move \qb64\TRAPOLE.exe \hamcalc64\prog\TRAPOLE.exe 
qb64 -c \hamcalc64\prog\TRAPROP.BAS 
move \qb64\TRAPROP.exe \hamcalc64\prog\TRAPROP.exe 
qb64 -c \hamcalc64\prog\TRIG.BAS 
move \qb64\TRIG.exe \hamcalc64\prog\TRIG.exe 
qb64 -c \hamcalc64\prog\TRIMR.BAS 
move \qb64\TRIMR.exe \hamcalc64\prog\TRIMR.exe 
qb64 -c \hamcalc64\prog\TRIPLAN.BAS 
move \qb64\TRIPLAN.exe \hamcalc64\prog\TRIPLAN.exe 
qb64 -c \hamcalc64\prog\TRISQU.BAS 
move \qb64\TRISQU.exe \hamcalc64\prog\TRISQU.exe 
qb64 -c \hamcalc64\prog\TRUNORTH.BAS 
move \qb64\TRUNORTH.exe \hamcalc64\prog\TRUNORTH.exe 
qb64 -c \hamcalc64\prog\TSFD.BAS 
move \qb64\TSFD.exe \hamcalc64\prog\TSFD.exe 
qb64 -c \hamcalc64\prog\TUNECCT.BAS 
move \qb64\TUNECCT.exe \hamcalc64\prog\TUNECCT.exe 
qb64 -c \hamcalc64\prog\TURNRAD.BAS 
move \qb64\TURNRAD.exe \hamcalc64\prog\TURNRAD.exe 
qb64 -c \hamcalc64\prog\TURNS.BAS 
move \qb64\TURNS.exe \hamcalc64\prog\TURNS.exe 
qb64 -c \hamcalc64\prog\TVCHAN.BAS 
move \qb64\TVCHAN.exe \hamcalc64\prog\TVCHAN.exe 
qb64 -c \hamcalc64\prog\TWINTEE.BAS 
move \qb64\TWINTEE.exe \hamcalc64\prog\TWINTEE.exe 
qb64 -c \hamcalc64\prog\UNITVALU.BAS 
move \qb64\UNITVALU.exe \hamcalc64\prog\UNITVALU.exe 
qb64 -c \hamcalc64\prog\VACAP.BAS 
move \qb64\VACAP.exe \hamcalc64\prog\VACAP.exe 
qb64 -c \hamcalc64\prog\VACAP14.BAS 
move \qb64\VACAP14.exe \hamcalc64\prog\VACAP14.exe 
qb64 -c \hamcalc64\prog\VACAP7.BAS 
move \qb64\VACAP7.exe \hamcalc64\prog\VACAP7.exe 
qb64 -c \hamcalc64\prog\VACAP8.BAS 
move \qb64\VACAP8.exe \hamcalc64\prog\VACAP8.exe 
qb64 -c \hamcalc64\prog\VACAP9.BAS 
move \qb64\VACAP9.exe \hamcalc64\prog\VACAP9.exe 
qb64 -c \hamcalc64\prog\VARAYFED.BAS 
move \qb64\VARAYFED.exe \hamcalc64\prog\VARAYFED.exe 
qb64 -c \hamcalc64\prog\VERTPATT.BAS 
move \qb64\VERTPATT.exe \hamcalc64\prog\VERTPATT.exe 
qb64 -c \hamcalc64\prog\VFOFREQ.BAS 
move \qb64\VFOFREQ.exe \hamcalc64\prog\VFOFREQ.exe 
qb64 -c \hamcalc64\prog\VOLTDIV.BAS 
move \qb64\VOLTDIV.exe \hamcalc64\prog\VOLTDIV.exe 
qb64 -c \hamcalc64\prog\WALKER.BAS 
move \qb64\WALKER.exe \hamcalc64\prog\WALKER.exe 
qb64 -c \hamcalc64\prog\WALWART.BAS 
move \qb64\WALWART.exe \hamcalc64\prog\WALWART.exe 
qb64 -c \hamcalc64\prog\WARTEST.BAS 
move \qb64\WARTEST.exe \hamcalc64\prog\WARTEST.exe 
qb64 -c \hamcalc64\prog\WATCH.BAS 
move \qb64\WATCH.exe \hamcalc64\prog\WATCH.exe 
qb64 -c \hamcalc64\prog\WAVETRAP.BAS 
move \qb64\WAVETRAP.exe \hamcalc64\prog\WAVETRAP.exe 
qb64 -c \hamcalc64\prog\WHEATSTO.BAS 
move \qb64\WHEATSTO.exe \hamcalc64\prog\WHEATSTO.exe 
qb64 -c \hamcalc64\prog\WINCHIL.BAS 
move \qb64\WINCHIL.exe \hamcalc64\prog\WINCHIL.exe 
qb64 -c \hamcalc64\prog\WINDCHIL.BAS 
move \qb64\WINDCHIL.exe \hamcalc64\prog\WINDCHIL.exe 
qb64 -c \hamcalc64\prog\WINDING.BAS 
move \qb64\WINDING.exe \hamcalc64\prog\WINDING.exe 
qb64 -c \hamcalc64\prog\WINDOM.BAS 
move \qb64\WINDOM.exe \hamcalc64\prog\WINDOM.exe 
qb64 -c \hamcalc64\prog\WIREANT.BAS 
move \qb64\WIREANT.exe \hamcalc64\prog\WIREANT.exe 
qb64 -c \hamcalc64\prog\WIRECOND.BAS 
move \qb64\WIRECOND.exe \hamcalc64\prog\WIRECOND.exe 
qb64 -c \hamcalc64\prog\WIREMESH.BAS 
move \qb64\WIREMESH.exe \hamcalc64\prog\WIREMESH.exe 
qb64 -c \hamcalc64\prog\WIREPEOP.BAS 
move \qb64\WIREPEOP.exe \hamcalc64\prog\WIREPEOP.exe 
qb64 -c \hamcalc64\prog\WIREPROP.BAS 
move \qb64\WIREPROP.exe \hamcalc64\prog\WIREPROP.exe 
qb64 -c \hamcalc64\prog\WIRESAG.BAS 
move \qb64\WIRESAG.exe \hamcalc64\prog\WIRESAG.exe 
qb64 -c \hamcalc64\prog\WORKS.BAS 
move \qb64\WORKS.exe \hamcalc64\prog\WORKS.exe 
qb64 -c \hamcalc64\prog\WX.BAS 
move \qb64\WX.exe \hamcalc64\prog\WX.exe 
qb64 -c \hamcalc64\prog\XFMR.BAS 
move \qb64\XFMR.exe \hamcalc64\prog\XFMR.exe 
qb64 -c \hamcalc64\prog\XFMRNARO.BAS 
move \qb64\XFMRNARO.exe \hamcalc64\prog\XFMRNARO.exe 
qb64 -c \hamcalc64\prog\XMTRZMAT.BAS 
move \qb64\XMTRZMAT.exe \hamcalc64\prog\XMTRZMAT.exe 
qb64 -c \hamcalc64\prog\XOVER.BAS 
move \qb64\XOVER.exe \hamcalc64\prog\XOVER.exe 
qb64 -c \hamcalc64\prog\YAGI3EL.BAS 
move \qb64\YAGI3EL.exe \hamcalc64\prog\YAGI3EL.exe 
qb64 -c \hamcalc64\prog\YAGILONG.BAS 
move \qb64\YAGILONG.exe \hamcalc64\prog\YAGILONG.exe 
qb64 -c \hamcalc64\prog\YAGISPAC.BAS 
move \qb64\YAGISPAC.exe \hamcalc64\prog\YAGISPAC.exe 
qb64 -c \hamcalc64\prog\YAGLONG.BAS 
move \qb64\YAGLONG.exe \hamcalc64\prog\YAGLONG.exe 
qb64 -c \hamcalc64\prog\YAGTAPER.BAS 
move \qb64\YAGTAPER.exe \hamcalc64\prog\YAGTAPER.exe 
qb64 -c \hamcalc64\prog\ZENER.BAS 
move \qb64\ZENER.exe \hamcalc64\prog\ZENER.exe 
qb64 -c \hamcalc64\prog\ZEPP.BAS 
move \qb64\ZEPP.exe \hamcalc64\prog\ZEPP.exe 
qb64 -c \hamcalc64\prog\ZEPPDBL.BAS 
move \qb64\ZEPPDBL.exe \hamcalc64\prog\ZEPPDBL.exe 
qb64 -c \hamcalc64\prog\ZEXIT.BAS 
move \qb64\ZEXIT.exe \hamcalc64\prog\ZEXIT.exe 
qb64 -c \hamcalc64\prog\ZOSTEPUP.BAS 
move \qb64\ZOSTEPUP.exe \hamcalc64\prog\ZOSTEPUP.exe 
qb64 -c \hamcalc64\prog\ZOUNDS.BAS 
move \qb64\ZOUNDS.exe \hamcalc64\prog\ZOUNDS.exe 
